[package]
name = "advent_2025"
version = "0.1.0"
edition = "2024"

[dependencies]
common.workspace = true
grid.workspace = true
regex.workspace = true
fancy-regex.workspace = true
rayon = "1.10"

[dev-dependencies]
criterion.workspace = true

[[bench]]
name = "day4_bench"
harness = false
